#!/bin/bash

# This is set as `SHELL` in the crontab, and wraps `/bin/sh`. It is used to
# redirect job output to syslog, to prevent logs from getting lost in the
# absence of a mailer for cron.
#
# Simply redirecting /proc/1/fd/2 is not possible, because non-root does not
# have permissions.

# Find a nice name for the syslog tag.
# Cron runs us as: $SHELL -c '<command>'
read -ra cmd <<< "$2"
tag="$(basename "${cmd[0]}")"

# ABC-specific: Get the console subcommand.
if [[ "$tag" == "console" ]]; then
  tag="${cmd[1]}"
fi

# Add PID, as is tradition.
tag+="[$$]"

# Redirect stdout/stderr to syslog.
exec 1> >(logger -t "$tag") 2>&1

# Exec command.
exec /bin/sh "$@"
